- name: Configuro lo switch del rack
  hosts: switchRack
  gather_facts: no
  tasks:
    - name: Crea vlan 99 per il traffico della lan gia' esistente nel laboratorio 522 del centro rete con vid 185
      cisco.ios.ios_vlans:
        config:
          - name: LAN_LAB_522
            vlan_id: 99
            shutdown: disabled

    - name: Creo la WAN fornita dal centro rete fornita dal centro rete con VID 186
      cisco.ios.ios_vlans:
        config:
          - name: WAN
            vlan_id: 186
            shutdown: disabled

    - name: Creo le vlan per i banchi singoli, ovvero 10, 20, 30, 40, 50, 60
      cisco.ios.ios_vlans:
        config:
          - name: vlan_banco_1
            vlan_id: 10
            shutdown: disabled

          - name: vlan_banco_2
            vlan_id: 20
            shutdown: disabled

          - name: vlan_banco_3
            vlan_id: 30
            shutdown: disabled

          - name: vlan_banco_4
            vlan_id: 40
            shutdown: disabled

          - name: vlan_banco_5
            vlan_id: 50
            shutdown: disabled

          - name: vlan_banco_6
            vlan_id: 60
            shutdown: disabled


    - name: Crea vlan 101 per la VLAN per il corso centraline
      cisco.ios.ios_vlans:
        config:
          - name: Centraline
            vlan_id: 101
            shutdown: disabled

    - name: Prima di impostare la porta trunk bisogna eseguire il comando switchport trunk encapsulation dot1q e imposto anche una descrizione
      ansible.netcommon.cli_command:
        command: |+
          configure terminal
          interface {{ item.interfaccia }}
          description {{ item.descrizione }}
          switchport trunk encapsulation dot1q
          exit
          exit
      loop:
        - { interfaccia: "GigabitEthernet 0/24", descrizione: "Porta di collegamento verso la vlan gia presente nel lab e per la rete libera" }
        - { interfaccia: "GigabitEthernet 0/23", descrizione: "Porta di collegamento con il proxmox" }
        - { interfaccia: "GigabitEthernet 0/21", descrizione: "Porta Access Point numero 1" }
        - { interfaccia: "GigabitEthernet 0/19", descrizione: "Porta Cisco Rack" }
        - { interfaccia: "GigabitEthernet 0/2", descrizione: "Switch Banco1" }
        - { interfaccia: "GigabitEthernet 0/3", descrizione: "Switch Banco2" }
        - { interfaccia: "GigabitEthernet 0/4", descrizione: "Switch Banco3" }
        - { interfaccia: "GigabitEthernet 0/5", descrizione: "Switch Banco4" }
        - { interfaccia: "GigabitEthernet 0/6", descrizione: "Switch Banco5" }
        - { interfaccia: "GigabitEthernet 0/7", descrizione: "Switch Banco6" }

    - name: Configurazione porte da 2 a 7 per i banchi, la 19 per il rack, la 21 per l'access point, la 23 per il proxmox e la 24 per il laboratorio e la rete libera
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.name }}"
            mode: trunk
            trunk:
              encapsulation: dot1q
              allowed_vlans: "{{ item.vlans }}"
              native_vlan: "{{ item.untagged }}"
        state: replaced
      loop:
        - { name: "GigabitEthernet0/24", vlans: [99, 186], untagged: 99 }
        - { name: "GigabitEthernet0/23", vlans: [1, 10, 20, 30, 40, 50, 60, 99, 186, 101], untagged: 1 }
        - { name: "GigabitEthernet0/21", vlans: [1, 10, 20, 30, 30, 50, 60, 99, 101], untagged: 1 }
        - { name: "GigabitEthernet0/19", vlans: [1, 10, 20, 30, 40, 50, 60, 99, 100], untagged: 1 }
        - { name: "GigabitEthernet0/2", vlans: [1, 10, 20, 30, 40, 50, 60, 99], untagged: 1 }
        - { name: "GigabitEthernet0/3", vlans: [1, 10, 20, 30, 40, 50, 60, 99], untagged: 1 }
        - { name: "GigabitEthernet0/4", vlans: [1, 10, 20, 30, 40, 50, 60, 99], untagged: 1 }
        - { name: "GigabitEthernet0/5", vlans: [1, 10, 20, 30, 40, 50, 60, 99], untagged: 1 }
        - { name: "GigabitEthernet0/6", vlans: [1, 10, 20, 30, 40, 50, 60, 99], untagged: 1 }
        - { name: "GigabitEthernet0/7", vlans: [1, 10, 20, 30, 40, 50, 60, 99], untagged: 1 }

    - name: Salvo la configurazione
      ansible.netcommon.cli_command:
        command: write
