- name: Configuro lo switch del rack
  hosts: switchRack
  gather_facts: no
  tasks:
    - name: Crea vlan 99 per il traffico della lan gia' esistente nel laboratorio 522
      cisco.ios.ios_vlans:
        config:
          - name: LAN_LAB_522
            vlan_id: 99
            shutdown: disabled

    - name: Crea vlan 100 per la WAN fornita dal Liberator
      cisco.ios.ios_vlans:
        config:
          - name: WAN
            vlan_id: 100
            shutdown: disabled

    - name: Creo le vlan per i banchi singoli, ovvero 10, 20, 30, 40, 50, 60
      cisco.ios.ios_vlans:
        config:
          - name: vlan_banco_1
            vlan_id: 10
            shutdown: disabled

          - name: vlan_banco_2
            vlan_id: 20
            shutdown: disabled

          - name: vlan_banco_3
            vlan_id: 30
            shutdown: disabled

          - name: vlan_banco_4
            vlan_id: 40
            shutdown: disabled

          - name: vlan_banco_5
            vlan_id: 50
            shutdown: disabled

          - name: vlan_banco_6
            vlan_id: 60
            shutdown: disabled

    - name: Prima di impostare la porta trunk bisogna eseguire il comando switchport trunk encapsulation dot1q e imposto anche una descrizione
      ansible.netcommon.cli_command:
        command: |+
          configure terminal
          interface {{ item.interfaccia }}
          description {{ item.descrizione }}
          switchport trunk encapsulation dot1q
          exit
          exit
      loop:
        - { interfaccia: "GigabitEthernet 0/23", descrizione: "Porta di collegamento con il proxmox" }
        - { interfaccia: "GigabitEthernet 0/21", descrizione: "Porta Access Point" }
        - { interfaccia: "GigabitEthernet 0/19", descrizione: "Porta Cisco Rack" }
        - { interfaccia: "GigabitEthernet 0/2", descrizione: "Switch Banco1" }
        - { interfaccia: "GigabitEthernet 0/3", descrizione: "Switch Banco2" }
        - { interfaccia: "GigabitEthernet 0/4", descrizione: "Switch Banco3" }
        - { interfaccia: "GigabitEthernet 0/5", descrizione: "Switch Banco4" }
        - { interfaccia: "GigabitEthernet 0/6", descrizione: "Switch Banco5" }
        - { interfaccia: "GigabitEthernet 0/7", descrizione: "Switch Banco6" }

    - name: Configurazione porte da 2 a 7, 19, 21 e 23 in mod trunk con consentite le vlan 1 e 99 con nativa la 1
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.name }}"
            mode: trunk
            trunk:
              encapsulation: dot1q
              allowed_vlans: "{{ item.vlans }}"
              native_vlan: "{{ item.untagged }}"
        state: merged
      loop:
        - { name: "GigabitEthernet0/23", vlans: [1, 10, 20, 30, 40, 50, 60, 99, 100], untagged: 1 }
        - { name: "GigabitEthernet0/21", vlans: [1, 10, 20, 30, 30, 50, 60, 99], untagged: 1 }
        - { name: "GigabitEthernet0/19", vlans: [1, 10, 20, 30, 40, 50, 60, 99, 100], untagged: 1 }
        - { name: "GigabitEthernet0/2", vlans: [1, 10, 20, 30, 40, 50, 60, 99], untagged: 1 }
        - { name: "GigabitEthernet0/3", vlans: [1, 10, 20, 30, 40, 50, 60, 99], untagged: 1 }
        - { name: "GigabitEthernet0/4", vlans: [1, 10, 20, 30, 40, 50, 60, 99], untagged: 1 }
        - { name: "GigabitEthernet0/5", vlans: [1, 10, 20, 30, 40, 50, 60, 99], untagged: 1 }
        - { name: "GigabitEthernet0/6", vlans: [1, 10, 20, 30, 40, 50, 60, 99], untagged: 1 }
        - { name: "GigabitEthernet0/7", vlans: [1, 10, 20, 30, 40, 50, 60, 99], untagged: 1 }

    - name: Assegno un nome alla GigabitEthernet 0/24 e alla GigabitEthernet 0/22
      ansible.netcommon.cli_command:
        command: |+
          configure terminal
          interface GigabitEthernet 0/24
          description Porta access alla VLAN preesistente nel laboratorio
          exit
          interface GigabitEthernet 0/22
          description WAN fornita dal liberator
          exit
          interface GigabitEthernet 0/18
          description Porta di collegamento per il raspberry Pi
          exit
          exit

    - name: Definisco le interfacce con l'esterno, ovvero la 22 (WAN) e la 24 (LAN_LAB_522)
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet0/22
            mode: access
            access:
              vlan: 100
          - name: GigabitEthernet0/24
            mode: access
            access:
              vlan: 99
          - name: GigabitEthernet0/18
            mode: access
            access:
              vlan: 99


    - name: Salvo la configurazione
      ansible.netcommon.cli_command:
        command: write
