- name: Configuro lo switch del rack
  hosts: switchRack
  gather_facts: no
  tasks:
    - name: Crea vlan 99 per il traffico della lan gia' esistente nel laboratorio 522
      cisco.ios.ios_vlans:
        config:
          - name: LAN_LAB_522
            vlan_id: 99
            shutdown: disabled
            activate: active

    - name: Configurazione porta Gig0/22 in mod trunk con consentite le vlan 1 e 99 con nativa la 1
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet0/22
            mode: trunk
            trunk:
              encapsulation: dot1q
              allowed_vlans: 1,99
              native_vlan: 1
        state: merged

    - name: Salvo la configurazione
      ansible.netcommon.cli_command:
        command: write
